language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - MATRIX_EVAL="chmod +x ./ci-script/linux-gcc.sh && ./ci-script/linux-gcc.sh"
    - os: linux
      dist: trusty
      sudo: required
      env:
        - MATRIX_EVAL="chmod +x ./ci-script/linux-clang.sh && ./ci-script/linux-clang.sh"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="chmod +x ./ci-script/darwin-gcc.sh && ./ci-script/darwin-gcc.sh"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="chmod +x ./ci-script/darwin-clang.sh && ./ci-script/darwin-clang.sh"

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./LML/LMLTest
    - ./LVM/LVMTest
