language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - MATRIX_EVAL="chmod +x ./linux-gcc.sh && ./linux-gcc.sh"
    - os: linux
      dist: trusty
      sudo: required
      env:
        - MATRIX_EVAL="chmod +x ./linux-clang.sh && ./linux-clang.sh"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="chmod +x ./darwin-gcc.sh && ./darwin-gcc.sh"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="chmod +x ./darwin-clang.sh && ./darwin-clang.sh"

before_install:
    - cd ./ci-script
    - eval "${MATRIX_EVAL}"
    - cd ..

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./LML/LMLTest
    - ./LVM/LVMTest
