language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      env:
        - MATRIX_EVAL="chmod +x linux-ci-clang.sh && ./linux-ci-clang.sh && CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="brew update && rm '/usr/local/include/c++' && brew install gcc && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="brew update"

before_install:
    - eval "${MATRIX_EVAL}"
    - curl -o cmake-3.11.0.tar.gz https://cmake.org/files/v3.11/cmake-3.11.0.tar.gz
    - tar -zxf cmake-3.11.0.tar.gz
    - cd cmake-3.11.0
    - ./bootstrap && make && make install

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./LML/LMLTest
    - ./LVM/LVMTest
